# Generated by Django 3.1.4 on 2020-12-07 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('serial_number', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('manufacturer', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Aircrafts',
                'ordering': ['manufacturer'],
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('icao_code', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('inflight_time', models.IntegerField(null=True)),
                ('aircraft', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='app.aircraft')),
                ('arrival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights_arrival', to='app.airport')),
                ('departure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights_departure', to='app.airport')),
            ],
            options={
                'verbose_name_plural': 'Flights',
                'ordering': ['departure_time', 'arrival_time'],
            },
        ),
    ]
